language: node_js
os: linux
node_js:
    - 12
sudo: false
cache: yarn
install: yarn
script:
    - yarn global add now
    - yarn global add codecov
    - yarn build
after_success:
    - codecov -f coverage/*.json
deploy:
    provider: script
    script: now --token=$NOW_TOKEN --prod
    cleanup: false
    if: tag IS present
    on:
        branch: master
notifications:
    email:
        recipients:
            - opensource@tagproject.ru
        on_failure: always
