language: node_js
sudo: false
cache: yarn
install: yarn
script:
    - yarn add now -g
    - yarn add codecov -g
    - yarn build
after_success:
    - codecov -f coverage/*.json
jobs:
    include:
        - stage: Deploy
          if: tag IS present
          node_js: 12
          os: linux
          provider: script
          script: now --token=$NOW_TOKEN --prod
notifications:
    email:
        recipients:
            - opensource@tagproject.ru
        on_failure: always
